/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WESENSE_HOMEBREW_V2_PROTO_WESENSE_HOMEBREW_V2_PB_H_INCLUDED
#define PB_WESENSE_HOMEBREW_V2_PROTO_WESENSE_HOMEBREW_V2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* BoardType - Collapsed from Vendor/ProductLine/DeviceType (v2.1)
 Saves ~4 bytes per message vs separate enums
 v2.3: Expanded to include Meshtastic hardware types and more ESP32 variants */
typedef enum _wesense_homebrew_v2_BoardType {
    wesense_homebrew_v2_BoardType_BOARD_UNKNOWN = 0,
    /* LilyGo boards (1-19) */
    wesense_homebrew_v2_BoardType_LILYGO_T3_S3 = 1,
    wesense_homebrew_v2_BoardType_LILYGO_T_BEAM = 2,
    wesense_homebrew_v2_BoardType_LILYGO_T_BEAM_S3 = 3,
    wesense_homebrew_v2_BoardType_LILYGO_T3_LORA32 = 4,
    wesense_homebrew_v2_BoardType_LILYGO_T3_S3_V1_3 = 5,
    wesense_homebrew_v2_BoardType_LILYGO_T3_S3_LR1121 = 6,
    wesense_homebrew_v2_BoardType_LILYGO_T_BEAM_V0_7 = 7,
    wesense_homebrew_v2_BoardType_LILYGO_T_BEAM_S3_CORE = 8,
    wesense_homebrew_v2_BoardType_LILYGO_T_ECHO = 9,
    wesense_homebrew_v2_BoardType_LILYGO_T_DECK = 10,
    wesense_homebrew_v2_BoardType_LILYGO_TLORA_V1 = 11,
    wesense_homebrew_v2_BoardType_LILYGO_TLORA_V2_1_1P6 = 12,
    /* Heltec boards (20-29) */
    wesense_homebrew_v2_BoardType_HELTEC_WIFI_LORA_32_V2 = 20,
    wesense_homebrew_v2_BoardType_HELTEC_WIFI_LORA_32_V3 = 21,
    wesense_homebrew_v2_BoardType_HELTEC_WIRELESS_STICK_LITE_V3 = 22,
    wesense_homebrew_v2_BoardType_HELTEC_WIRELESS_TRACKER = 23,
    wesense_homebrew_v2_BoardType_HELTEC_WIRELESS_PAPER = 24,
    wesense_homebrew_v2_BoardType_HELTEC_HT62 = 25,
    /* RAK Wireless boards (30-39) */
    wesense_homebrew_v2_BoardType_RAK4631 = 30,
    wesense_homebrew_v2_BoardType_RAK11200 = 31,
    wesense_homebrew_v2_BoardType_RAK11310 = 32,
    /* Generic ESP32 variants (40-59) */
    wesense_homebrew_v2_BoardType_ESP32_DEVKIT = 40,
    wesense_homebrew_v2_BoardType_ESP32_S2_DEVKIT = 41,
    wesense_homebrew_v2_BoardType_ESP32_S3_DEVKIT = 42,
    wesense_homebrew_v2_BoardType_ESP32_C3_DEVKIT = 43,
    wesense_homebrew_v2_BoardType_ESP32_C6_DEVKIT = 44,
    wesense_homebrew_v2_BoardType_ESP32_C2_DEVKIT = 45,
    wesense_homebrew_v2_BoardType_ESP32_H2_DEVKIT = 46,
    wesense_homebrew_v2_BoardType_ESP8266_D1_MINI = 47,
    /* DFRobot boards (60-69) */
    wesense_homebrew_v2_BoardType_DFROBOT_ESP32_C6_BEETLE = 60,
    /* Other manufacturers (70-79) */
    wesense_homebrew_v2_BoardType_STATION_G2 = 70,
    wesense_homebrew_v2_BoardType_CDEBYTE_EORA_S3 = 71,
    wesense_homebrew_v2_BoardType_RP2040_LORA = 72,
    wesense_homebrew_v2_BoardType_RPI_PICO = 73,
    /* DIY / Custom (80-89) */
    wesense_homebrew_v2_BoardType_CUSTOM_HOMEBREW = 80,
    wesense_homebrew_v2_BoardType_DIY_V1 = 81,
    wesense_homebrew_v2_BoardType_NRF52_PROMICRO_DIY = 82,
    wesense_homebrew_v2_BoardType_PORTDUINO = 83,
    wesense_homebrew_v2_BoardType_PRIVATE_HW = 84,
    /* Pre-calibrated commercial (100+) */
    wesense_homebrew_v2_BoardType_WESENSE_SENTINEL = 100,
    wesense_homebrew_v2_BoardType_WESENSE_SCOUT = 101
} wesense_homebrew_v2_BoardType;

/* CalibrationStatus - Current state of sensor calibration */
typedef enum _wesense_homebrew_v2_CalibrationStatus {
    wesense_homebrew_v2_CalibrationStatus_CALIBRATION_UNKNOWN = 0,
    wesense_homebrew_v2_CalibrationStatus_UNCALIBRATED = 1, /* Factory default, no calibration */
    wesense_homebrew_v2_CalibrationStatus_CALIBRATING = 2, /* ASC in progress, learning */
    wesense_homebrew_v2_CalibrationStatus_FACTORY_CALIBRATED = 3, /* Factory calibration only */
    wesense_homebrew_v2_CalibrationStatus_FIELD_CALIBRATED = 4 /* FRC or ASC complete */
} wesense_homebrew_v2_CalibrationStatus;

/* CalibrationMethod - How the sensor was calibrated */
typedef enum _wesense_homebrew_v2_CalibrationMethod {
    wesense_homebrew_v2_CalibrationMethod_METHOD_UNKNOWN = 0,
    wesense_homebrew_v2_CalibrationMethod_FACTORY = 1, /* Manufacturer calibration */
    wesense_homebrew_v2_CalibrationMethod_ASC_LEARNING = 2, /* Automatic Self-Calibration in progress */
    wesense_homebrew_v2_CalibrationMethod_ASC_COMPLETE = 3, /* ASC established baseline */
    wesense_homebrew_v2_CalibrationMethod_FRC_MANUAL = 4, /* Forced Recalibration performed */
    wesense_homebrew_v2_CalibrationMethod_REFERENCE_GAS = 5 /* Calibrated against reference gas */
} wesense_homebrew_v2_CalibrationMethod;

/* ReadingType - What is being measured */
typedef enum _wesense_homebrew_v2_ReadingType {
    wesense_homebrew_v2_ReadingType_READING_UNKNOWN = 0,
    wesense_homebrew_v2_ReadingType_TEMPERATURE = 1, /* °C */
    wesense_homebrew_v2_ReadingType_HUMIDITY = 2, /* %RH */
    wesense_homebrew_v2_ReadingType_CO2 = 3, /* ppm */
    wesense_homebrew_v2_ReadingType_PRESSURE = 4, /* hPa */
    wesense_homebrew_v2_ReadingType_PM1 = 5, /* µg/m³ */
    wesense_homebrew_v2_ReadingType_PM2_5 = 6, /* µg/m³ (renamed from PM25 for clarity) */
    wesense_homebrew_v2_ReadingType_PM10 = 7, /* µg/m³ */
    wesense_homebrew_v2_ReadingType_VOC_INDEX = 8, /* 0-500 index */
    wesense_homebrew_v2_ReadingType_NOX_INDEX = 9, /* 0-500 index */
    wesense_homebrew_v2_ReadingType_VOLTAGE = 10, /* V */
    wesense_homebrew_v2_ReadingType_CURRENT = 11, /* mA */
    wesense_homebrew_v2_ReadingType_POWER = 12, /* mW */
    wesense_homebrew_v2_ReadingType_BATTERY_LEVEL = 13, /* % */
    wesense_homebrew_v2_ReadingType_GAS_RESISTANCE = 14, /* kOhm (BME680) */
    /* Extended particle counts (WiFi only, v2.1) */
    wesense_homebrew_v2_ReadingType_PC_03UM = 20, /* count/L (>0.3µm) */
    wesense_homebrew_v2_ReadingType_PC_05UM = 21, /* count/L (>0.5µm) */
    wesense_homebrew_v2_ReadingType_PC_10UM = 22, /* count/L (>1.0µm) */
    wesense_homebrew_v2_ReadingType_PC_25UM = 23, /* count/L (>2.5µm) */
    wesense_homebrew_v2_ReadingType_PC_50UM = 24, /* count/L (>5.0µm) */
    wesense_homebrew_v2_ReadingType_PC_100UM = 25 /* count/L (>10µm) */
} wesense_homebrew_v2_ReadingType;

/* SensorModel - Which sensor IC produced the reading */
typedef enum _wesense_homebrew_v2_SensorModel {
    wesense_homebrew_v2_SensorModel_SENSOR_UNKNOWN = 0,
    wesense_homebrew_v2_SensorModel_SHT4X = 1, /* Sensirion temp/humidity */
    wesense_homebrew_v2_SensorModel_AHT20 = 2, /* Aosong temp/humidity */
    wesense_homebrew_v2_SensorModel_SCD4X = 3, /* Sensirion CO2 */
    wesense_homebrew_v2_SensorModel_BMP280 = 4, /* Bosch pressure */
    wesense_homebrew_v2_SensorModel_BME280 = 5, /* Bosch pressure/humidity */
    wesense_homebrew_v2_SensorModel_BME680 = 6, /* Bosch pressure/humidity/VOC */
    wesense_homebrew_v2_SensorModel_SGP41 = 7, /* Sensirion VOC/NOx */
    wesense_homebrew_v2_SensorModel_PMS5003 = 8, /* Plantower PM sensor */
    wesense_homebrew_v2_SensorModel_INA219 = 9, /* TI current/voltage */
    wesense_homebrew_v2_SensorModel_BMP390 = 10, /* Bosch pressure (high precision) */
    wesense_homebrew_v2_SensorModel_SCD30 = 11, /* Sensirion CO2 (older model) */
    wesense_homebrew_v2_SensorModel_CM1106C = 12, /* Cubic CM1106-C NDIR CO2 (I2C or UART) */
    wesense_homebrew_v2_SensorModel_TMP117 = 13, /* TI high-precision temperature (±0.1°C) */
    wesense_homebrew_v2_SensorModel_AXP2101 = 14 /* X-Powers PMU (battery management) */
} wesense_homebrew_v2_SensorModel;

/* DeploymentType - Indoor/Outdoor classification */
typedef enum _wesense_homebrew_v2_DeploymentType {
    wesense_homebrew_v2_DeploymentType_DEPLOYMENT_UNKNOWN = 0,
    wesense_homebrew_v2_DeploymentType_INDOOR = 1,
    wesense_homebrew_v2_DeploymentType_OUTDOOR = 2,
    wesense_homebrew_v2_DeploymentType_MIXED = 3 /* e.g., garage, covered outdoor */
} wesense_homebrew_v2_DeploymentType;

typedef enum _wesense_homebrew_v2_Vendor {
    wesense_homebrew_v2_Vendor_VENDOR_UNKNOWN = 0,
    wesense_homebrew_v2_Vendor_WESENSE = 1,
    wesense_homebrew_v2_Vendor_MESHTASTIC = 2,
    wesense_homebrew_v2_Vendor_PURPLEAIR = 3,
    wesense_homebrew_v2_Vendor_AWAIR = 4
} wesense_homebrew_v2_Vendor;

typedef enum _wesense_homebrew_v2_ProductLine {
    wesense_homebrew_v2_ProductLine_PRODUCT_UNKNOWN = 0,
    wesense_homebrew_v2_ProductLine_HOMEBREW = 1,
    wesense_homebrew_v2_ProductLine_SENTINEL = 2,
    wesense_homebrew_v2_ProductLine_SCOUT = 3,
    wesense_homebrew_v2_ProductLine_COMMUNITY = 4,
    wesense_homebrew_v2_ProductLine_OFFICIAL = 5
} wesense_homebrew_v2_ProductLine;

typedef enum _wesense_homebrew_v2_DeviceType {
    wesense_homebrew_v2_DeviceType_DEVICE_UNKNOWN = 0,
    wesense_homebrew_v2_DeviceType_BEACON = 1,
    wesense_homebrew_v2_DeviceType_WATCHPOINT = 2,
    wesense_homebrew_v2_DeviceType_DEVICE_SCOUT = 3,
    wesense_homebrew_v2_DeviceType_RELAY = 4,
    wesense_homebrew_v2_DeviceType_NODE = 5,
    wesense_homebrew_v2_DeviceType_STATION = 6
} wesense_homebrew_v2_DeviceType;

typedef enum _wesense_homebrew_v2_LocationSource {
    wesense_homebrew_v2_LocationSource_LOCATION_UNKNOWN = 0,
    wesense_homebrew_v2_LocationSource_GPS_ACTIVE = 1,
    wesense_homebrew_v2_LocationSource_STATIC_HARDCODED = 2,
    wesense_homebrew_v2_LocationSource_REMOTE_MQTT = 3
} wesense_homebrew_v2_LocationSource;

/* TransportType - Kept for reference but NOT used in messages
 Transport is inferred from MQTT topic by ingesters */
typedef enum _wesense_homebrew_v2_TransportType {
    wesense_homebrew_v2_TransportType_TRANSPORT_UNKNOWN = 0,
    wesense_homebrew_v2_TransportType_WIFI_MQTT = 1,
    wesense_homebrew_v2_TransportType_LORAWAN = 2,
    wesense_homebrew_v2_TransportType_TRANSPORT_MESHTASTIC = 3,
    wesense_homebrew_v2_TransportType_CELLULAR = 4,
    wesense_homebrew_v2_TransportType_SATELLITE = 5
} wesense_homebrew_v2_TransportType;

/* Struct definitions */
/* Individual sensor measurement

 Size: ~7 bytes (LoRa), ~8 bytes (WiFi with calibration)
 - ReadingType enum (1-2 bytes)
 - float value (5 bytes)
 - SensorModel enum (1 byte, optional)
 - CalibrationStatus (1 byte, optional, WiFi only) */
typedef struct _wesense_homebrew_v2_SensorValue {
    wesense_homebrew_v2_ReadingType reading_type; /* What is being measured */
    float value; /* The measurement value */
    wesense_homebrew_v2_SensorModel sensor_model; /* Which sensor IC (optional) */
    wesense_homebrew_v2_CalibrationStatus calibration; /* Calibration state (optional, WiFi only) */
} wesense_homebrew_v2_SensorValue;

/* Per-sensor calibration info (used in DeviceMetadataV2) */
typedef struct _wesense_homebrew_v2_SensorCalibration {
    wesense_homebrew_v2_SensorModel sensor_model; /* Which sensor */
    wesense_homebrew_v2_CalibrationStatus status; /* Current calibration state */
    wesense_homebrew_v2_CalibrationMethod method; /* How it was calibrated */
    uint32_t calibration_date; /* When calibrated (Unix epoch) */
} wesense_homebrew_v2_SensorCalibration;

/* SensorReadingV2 - Frequent sensor data message

 Sent every 5-10 minutes with current sensor values.

 LoRa sensors: Send only required fields (device_id, timestamp, measurements)
 WiFi sensors: Send all fields including location, board_type, node_name

 Size:
 - LoRa minimal (5 sensors): ~49 bytes
 - WiFi full (14 sensors): ~170 bytes */
typedef struct _wesense_homebrew_v2_SensorReadingV2 {
    /* === REQUIRED (always sent) === */
    uint64_t device_id; /* MAC address as uint64 (8 bytes) */
    uint32_t timestamp; /* Unix epoch seconds (4 bytes) */
    /* === WIFI ONLY (omit for LoRa to save bandwidth) === */
    int32_t latitude_e5; /* Latitude × 100000 (4 bytes) */
    int32_t longitude_e5; /* Longitude × 100000 (4 bytes) */
    int32_t altitude_cm; /* Altitude in cm (4 bytes) - v2.1 */
    wesense_homebrew_v2_BoardType board_type; /* Hardware type (1-2 bytes) - v2.1 */
    wesense_homebrew_v2_DeploymentType deployment_type; /* Indoor/Outdoor/Mixed (1 byte) */
    pb_size_t measurements_count;
    wesense_homebrew_v2_SensorValue measurements[14]; /* Sensor readings (variable) */
    char node_name[25]; /* Friendly name, max 24 chars - v2.1 */
    char node_info[65]; /* Physical setup description, max 64 chars - v2.2 */
    char node_info_url[97]; /* URL to detailed documentation, max 96 chars - v2.2 */
    /* === DEPRECATED (v2.0 compatibility) ===
 Use board_type instead for new implementations */
    wesense_homebrew_v2_Vendor vendor; /* Deprecated: use board_type */
    wesense_homebrew_v2_ProductLine product_line; /* Deprecated: use board_type */
    wesense_homebrew_v2_DeviceType device_type; /* Deprecated: use board_type */
} wesense_homebrew_v2_SensorReadingV2;

/* DeviceMetadataV2 - Infrequent device metadata message (v2.1)

 Sent on startup, daily, and when calibration status changes.
 Used by LoRa sensors to send metadata separately from readings.

 Size: ~90 bytes */
typedef struct _wesense_homebrew_v2_DeviceMetadataV2 {
    uint64_t device_id; /* MAC address as uint64 */
    uint32_t timestamp; /* When metadata was sent */
    /* Location (static for most deployments) */
    int32_t latitude_e5; /* Latitude × 100000 */
    int32_t longitude_e5; /* Longitude × 100000 */
    int32_t altitude_cm; /* Altitude in cm */
    /* Device identification */
    wesense_homebrew_v2_BoardType board_type; /* Hardware type */
    wesense_homebrew_v2_DeploymentType deployment_type; /* Indoor/Outdoor/Mixed */
    char node_name[25]; /* Friendly name, max 24 chars */
    char firmware_version[17]; /* e.g., "2.1.0", max 16 chars */
    /* Calibration status (per sensor type) */
    pb_size_t calibrations_count;
    wesense_homebrew_v2_SensorCalibration calibrations[10];
    char node_info[65]; /* Physical setup description, max 64 chars - v2.2 */
    char node_info_url[97]; /* URL to detailed documentation, max 96 chars - v2.2 */
} wesense_homebrew_v2_DeviceMetadataV2;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _wesense_homebrew_v2_BoardType_MIN wesense_homebrew_v2_BoardType_BOARD_UNKNOWN
#define _wesense_homebrew_v2_BoardType_MAX wesense_homebrew_v2_BoardType_WESENSE_SCOUT
#define _wesense_homebrew_v2_BoardType_ARRAYSIZE ((wesense_homebrew_v2_BoardType)(wesense_homebrew_v2_BoardType_WESENSE_SCOUT+1))

#define _wesense_homebrew_v2_CalibrationStatus_MIN wesense_homebrew_v2_CalibrationStatus_CALIBRATION_UNKNOWN
#define _wesense_homebrew_v2_CalibrationStatus_MAX wesense_homebrew_v2_CalibrationStatus_FIELD_CALIBRATED
#define _wesense_homebrew_v2_CalibrationStatus_ARRAYSIZE ((wesense_homebrew_v2_CalibrationStatus)(wesense_homebrew_v2_CalibrationStatus_FIELD_CALIBRATED+1))

#define _wesense_homebrew_v2_CalibrationMethod_MIN wesense_homebrew_v2_CalibrationMethod_METHOD_UNKNOWN
#define _wesense_homebrew_v2_CalibrationMethod_MAX wesense_homebrew_v2_CalibrationMethod_REFERENCE_GAS
#define _wesense_homebrew_v2_CalibrationMethod_ARRAYSIZE ((wesense_homebrew_v2_CalibrationMethod)(wesense_homebrew_v2_CalibrationMethod_REFERENCE_GAS+1))

#define _wesense_homebrew_v2_ReadingType_MIN wesense_homebrew_v2_ReadingType_READING_UNKNOWN
#define _wesense_homebrew_v2_ReadingType_MAX wesense_homebrew_v2_ReadingType_PC_100UM
#define _wesense_homebrew_v2_ReadingType_ARRAYSIZE ((wesense_homebrew_v2_ReadingType)(wesense_homebrew_v2_ReadingType_PC_100UM+1))

#define _wesense_homebrew_v2_SensorModel_MIN wesense_homebrew_v2_SensorModel_SENSOR_UNKNOWN
#define _wesense_homebrew_v2_SensorModel_MAX wesense_homebrew_v2_SensorModel_AXP2101
#define _wesense_homebrew_v2_SensorModel_ARRAYSIZE ((wesense_homebrew_v2_SensorModel)(wesense_homebrew_v2_SensorModel_AXP2101+1))

#define _wesense_homebrew_v2_DeploymentType_MIN wesense_homebrew_v2_DeploymentType_DEPLOYMENT_UNKNOWN
#define _wesense_homebrew_v2_DeploymentType_MAX wesense_homebrew_v2_DeploymentType_MIXED
#define _wesense_homebrew_v2_DeploymentType_ARRAYSIZE ((wesense_homebrew_v2_DeploymentType)(wesense_homebrew_v2_DeploymentType_MIXED+1))

#define _wesense_homebrew_v2_Vendor_MIN wesense_homebrew_v2_Vendor_VENDOR_UNKNOWN
#define _wesense_homebrew_v2_Vendor_MAX wesense_homebrew_v2_Vendor_AWAIR
#define _wesense_homebrew_v2_Vendor_ARRAYSIZE ((wesense_homebrew_v2_Vendor)(wesense_homebrew_v2_Vendor_AWAIR+1))

#define _wesense_homebrew_v2_ProductLine_MIN wesense_homebrew_v2_ProductLine_PRODUCT_UNKNOWN
#define _wesense_homebrew_v2_ProductLine_MAX wesense_homebrew_v2_ProductLine_OFFICIAL
#define _wesense_homebrew_v2_ProductLine_ARRAYSIZE ((wesense_homebrew_v2_ProductLine)(wesense_homebrew_v2_ProductLine_OFFICIAL+1))

#define _wesense_homebrew_v2_DeviceType_MIN wesense_homebrew_v2_DeviceType_DEVICE_UNKNOWN
#define _wesense_homebrew_v2_DeviceType_MAX wesense_homebrew_v2_DeviceType_STATION
#define _wesense_homebrew_v2_DeviceType_ARRAYSIZE ((wesense_homebrew_v2_DeviceType)(wesense_homebrew_v2_DeviceType_STATION+1))

#define _wesense_homebrew_v2_LocationSource_MIN wesense_homebrew_v2_LocationSource_LOCATION_UNKNOWN
#define _wesense_homebrew_v2_LocationSource_MAX wesense_homebrew_v2_LocationSource_REMOTE_MQTT
#define _wesense_homebrew_v2_LocationSource_ARRAYSIZE ((wesense_homebrew_v2_LocationSource)(wesense_homebrew_v2_LocationSource_REMOTE_MQTT+1))

#define _wesense_homebrew_v2_TransportType_MIN wesense_homebrew_v2_TransportType_TRANSPORT_UNKNOWN
#define _wesense_homebrew_v2_TransportType_MAX wesense_homebrew_v2_TransportType_SATELLITE
#define _wesense_homebrew_v2_TransportType_ARRAYSIZE ((wesense_homebrew_v2_TransportType)(wesense_homebrew_v2_TransportType_SATELLITE+1))

#define wesense_homebrew_v2_SensorValue_reading_type_ENUMTYPE wesense_homebrew_v2_ReadingType
#define wesense_homebrew_v2_SensorValue_sensor_model_ENUMTYPE wesense_homebrew_v2_SensorModel
#define wesense_homebrew_v2_SensorValue_calibration_ENUMTYPE wesense_homebrew_v2_CalibrationStatus

#define wesense_homebrew_v2_SensorCalibration_sensor_model_ENUMTYPE wesense_homebrew_v2_SensorModel
#define wesense_homebrew_v2_SensorCalibration_status_ENUMTYPE wesense_homebrew_v2_CalibrationStatus
#define wesense_homebrew_v2_SensorCalibration_method_ENUMTYPE wesense_homebrew_v2_CalibrationMethod

#define wesense_homebrew_v2_SensorReadingV2_board_type_ENUMTYPE wesense_homebrew_v2_BoardType
#define wesense_homebrew_v2_SensorReadingV2_deployment_type_ENUMTYPE wesense_homebrew_v2_DeploymentType
#define wesense_homebrew_v2_SensorReadingV2_vendor_ENUMTYPE wesense_homebrew_v2_Vendor
#define wesense_homebrew_v2_SensorReadingV2_product_line_ENUMTYPE wesense_homebrew_v2_ProductLine
#define wesense_homebrew_v2_SensorReadingV2_device_type_ENUMTYPE wesense_homebrew_v2_DeviceType

#define wesense_homebrew_v2_DeviceMetadataV2_board_type_ENUMTYPE wesense_homebrew_v2_BoardType
#define wesense_homebrew_v2_DeviceMetadataV2_deployment_type_ENUMTYPE wesense_homebrew_v2_DeploymentType


/* Initializer values for message structs */
#define wesense_homebrew_v2_SensorValue_init_default {_wesense_homebrew_v2_ReadingType_MIN, 0, _wesense_homebrew_v2_SensorModel_MIN, _wesense_homebrew_v2_CalibrationStatus_MIN}
#define wesense_homebrew_v2_SensorCalibration_init_default {_wesense_homebrew_v2_SensorModel_MIN, _wesense_homebrew_v2_CalibrationStatus_MIN, _wesense_homebrew_v2_CalibrationMethod_MIN, 0}
#define wesense_homebrew_v2_SensorReadingV2_init_default {0, 0, 0, 0, 0, _wesense_homebrew_v2_BoardType_MIN, _wesense_homebrew_v2_DeploymentType_MIN, 0, {wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default, wesense_homebrew_v2_SensorValue_init_default}, "", "", "", _wesense_homebrew_v2_Vendor_MIN, _wesense_homebrew_v2_ProductLine_MIN, _wesense_homebrew_v2_DeviceType_MIN}
#define wesense_homebrew_v2_DeviceMetadataV2_init_default {0, 0, 0, 0, 0, _wesense_homebrew_v2_BoardType_MIN, _wesense_homebrew_v2_DeploymentType_MIN, "", "", 0, {wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default, wesense_homebrew_v2_SensorCalibration_init_default}, "", ""}
#define wesense_homebrew_v2_SensorValue_init_zero {_wesense_homebrew_v2_ReadingType_MIN, 0, _wesense_homebrew_v2_SensorModel_MIN, _wesense_homebrew_v2_CalibrationStatus_MIN}
#define wesense_homebrew_v2_SensorCalibration_init_zero {_wesense_homebrew_v2_SensorModel_MIN, _wesense_homebrew_v2_CalibrationStatus_MIN, _wesense_homebrew_v2_CalibrationMethod_MIN, 0}
#define wesense_homebrew_v2_SensorReadingV2_init_zero {0, 0, 0, 0, 0, _wesense_homebrew_v2_BoardType_MIN, _wesense_homebrew_v2_DeploymentType_MIN, 0, {wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero, wesense_homebrew_v2_SensorValue_init_zero}, "", "", "", _wesense_homebrew_v2_Vendor_MIN, _wesense_homebrew_v2_ProductLine_MIN, _wesense_homebrew_v2_DeviceType_MIN}
#define wesense_homebrew_v2_DeviceMetadataV2_init_zero {0, 0, 0, 0, 0, _wesense_homebrew_v2_BoardType_MIN, _wesense_homebrew_v2_DeploymentType_MIN, "", "", 0, {wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero, wesense_homebrew_v2_SensorCalibration_init_zero}, "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define wesense_homebrew_v2_SensorValue_reading_type_tag 1
#define wesense_homebrew_v2_SensorValue_value_tag 2
#define wesense_homebrew_v2_SensorValue_sensor_model_tag 3
#define wesense_homebrew_v2_SensorValue_calibration_tag 4
#define wesense_homebrew_v2_SensorCalibration_sensor_model_tag 1
#define wesense_homebrew_v2_SensorCalibration_status_tag 2
#define wesense_homebrew_v2_SensorCalibration_method_tag 3
#define wesense_homebrew_v2_SensorCalibration_calibration_date_tag 4
#define wesense_homebrew_v2_SensorReadingV2_device_id_tag 1
#define wesense_homebrew_v2_SensorReadingV2_timestamp_tag 2
#define wesense_homebrew_v2_SensorReadingV2_latitude_e5_tag 3
#define wesense_homebrew_v2_SensorReadingV2_longitude_e5_tag 4
#define wesense_homebrew_v2_SensorReadingV2_altitude_cm_tag 5
#define wesense_homebrew_v2_SensorReadingV2_board_type_tag 6
#define wesense_homebrew_v2_SensorReadingV2_deployment_type_tag 7
#define wesense_homebrew_v2_SensorReadingV2_measurements_tag 10
#define wesense_homebrew_v2_SensorReadingV2_node_name_tag 11
#define wesense_homebrew_v2_SensorReadingV2_node_info_tag 12
#define wesense_homebrew_v2_SensorReadingV2_node_info_url_tag 13
#define wesense_homebrew_v2_SensorReadingV2_vendor_tag 15
#define wesense_homebrew_v2_SensorReadingV2_product_line_tag 16
#define wesense_homebrew_v2_SensorReadingV2_device_type_tag 17
#define wesense_homebrew_v2_DeviceMetadataV2_device_id_tag 1
#define wesense_homebrew_v2_DeviceMetadataV2_timestamp_tag 2
#define wesense_homebrew_v2_DeviceMetadataV2_latitude_e5_tag 3
#define wesense_homebrew_v2_DeviceMetadataV2_longitude_e5_tag 4
#define wesense_homebrew_v2_DeviceMetadataV2_altitude_cm_tag 5
#define wesense_homebrew_v2_DeviceMetadataV2_board_type_tag 6
#define wesense_homebrew_v2_DeviceMetadataV2_deployment_type_tag 7
#define wesense_homebrew_v2_DeviceMetadataV2_node_name_tag 8
#define wesense_homebrew_v2_DeviceMetadataV2_firmware_version_tag 9
#define wesense_homebrew_v2_DeviceMetadataV2_calibrations_tag 10
#define wesense_homebrew_v2_DeviceMetadataV2_node_info_tag 11
#define wesense_homebrew_v2_DeviceMetadataV2_node_info_url_tag 12

/* Struct field encoding specification for nanopb */
#define wesense_homebrew_v2_SensorValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reading_type,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2) \
X(a, STATIC,   SINGULAR, UENUM,    sensor_model,      3) \
X(a, STATIC,   SINGULAR, UENUM,    calibration,       4)
#define wesense_homebrew_v2_SensorValue_CALLBACK NULL
#define wesense_homebrew_v2_SensorValue_DEFAULT NULL

#define wesense_homebrew_v2_SensorCalibration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    sensor_model,      1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, UENUM,    method,            3) \
X(a, STATIC,   SINGULAR, FIXED32,  calibration_date,   4)
#define wesense_homebrew_v2_SensorCalibration_CALLBACK NULL
#define wesense_homebrew_v2_SensorCalibration_DEFAULT NULL

#define wesense_homebrew_v2_SensorReadingV2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  device_id,         1) \
X(a, STATIC,   SINGULAR, FIXED32,  timestamp,         2) \
X(a, STATIC,   SINGULAR, SFIXED32, latitude_e5,       3) \
X(a, STATIC,   SINGULAR, SFIXED32, longitude_e5,      4) \
X(a, STATIC,   SINGULAR, SFIXED32, altitude_cm,       5) \
X(a, STATIC,   SINGULAR, UENUM,    board_type,        6) \
X(a, STATIC,   SINGULAR, UENUM,    deployment_type,   7) \
X(a, STATIC,   REPEATED, MESSAGE,  measurements,     10) \
X(a, STATIC,   SINGULAR, STRING,   node_name,        11) \
X(a, STATIC,   SINGULAR, STRING,   node_info,        12) \
X(a, STATIC,   SINGULAR, STRING,   node_info_url,    13) \
X(a, STATIC,   SINGULAR, UENUM,    vendor,           15) \
X(a, STATIC,   SINGULAR, UENUM,    product_line,     16) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,      17)
#define wesense_homebrew_v2_SensorReadingV2_CALLBACK NULL
#define wesense_homebrew_v2_SensorReadingV2_DEFAULT NULL
#define wesense_homebrew_v2_SensorReadingV2_measurements_MSGTYPE wesense_homebrew_v2_SensorValue

#define wesense_homebrew_v2_DeviceMetadataV2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  device_id,         1) \
X(a, STATIC,   SINGULAR, FIXED32,  timestamp,         2) \
X(a, STATIC,   SINGULAR, SFIXED32, latitude_e5,       3) \
X(a, STATIC,   SINGULAR, SFIXED32, longitude_e5,      4) \
X(a, STATIC,   SINGULAR, SFIXED32, altitude_cm,       5) \
X(a, STATIC,   SINGULAR, UENUM,    board_type,        6) \
X(a, STATIC,   SINGULAR, UENUM,    deployment_type,   7) \
X(a, STATIC,   SINGULAR, STRING,   node_name,         8) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   9) \
X(a, STATIC,   REPEATED, MESSAGE,  calibrations,     10) \
X(a, STATIC,   SINGULAR, STRING,   node_info,        11) \
X(a, STATIC,   SINGULAR, STRING,   node_info_url,    12)
#define wesense_homebrew_v2_DeviceMetadataV2_CALLBACK NULL
#define wesense_homebrew_v2_DeviceMetadataV2_DEFAULT NULL
#define wesense_homebrew_v2_DeviceMetadataV2_calibrations_MSGTYPE wesense_homebrew_v2_SensorCalibration

extern const pb_msgdesc_t wesense_homebrew_v2_SensorValue_msg;
extern const pb_msgdesc_t wesense_homebrew_v2_SensorCalibration_msg;
extern const pb_msgdesc_t wesense_homebrew_v2_SensorReadingV2_msg;
extern const pb_msgdesc_t wesense_homebrew_v2_DeviceMetadataV2_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wesense_homebrew_v2_SensorValue_fields &wesense_homebrew_v2_SensorValue_msg
#define wesense_homebrew_v2_SensorCalibration_fields &wesense_homebrew_v2_SensorCalibration_msg
#define wesense_homebrew_v2_SensorReadingV2_fields &wesense_homebrew_v2_SensorReadingV2_msg
#define wesense_homebrew_v2_DeviceMetadataV2_fields &wesense_homebrew_v2_DeviceMetadataV2_msg

/* Maximum encoded size of messages (where known) */
#define WESENSE_HOMEBREW_V2_PROTO_WESENSE_HOMEBREW_V2_PB_H_MAX_SIZE wesense_homebrew_v2_SensorReadingV2_size
#define wesense_homebrew_v2_DeviceMetadataV2_size 371
#define wesense_homebrew_v2_SensorCalibration_size 11
#define wesense_homebrew_v2_SensorReadingV2_size 413
#define wesense_homebrew_v2_SensorValue_size     11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
