/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/wesense_homebrew_v2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wesense_homebrew_v2_SensorValue, wesense_homebrew_v2_SensorValue, AUTO)


PB_BIND(wesense_homebrew_v2_SensorCalibration, wesense_homebrew_v2_SensorCalibration, AUTO)


PB_BIND(wesense_homebrew_v2_SensorReadingV2, wesense_homebrew_v2_SensorReadingV2, 2)


PB_BIND(wesense_homebrew_v2_DeviceMetadataV2, wesense_homebrew_v2_DeviceMetadataV2, 2)

























